### ISSUE TITLE
Default smoothing 5 or 6 mm FWHM?

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_abcd#223]
When using the default smoothing option, the HTML output says a 6mm kernel was used, but the online documentation says 5mm. Thought I should point out the discrepency.

Thanks,
Steven

**Comment by a3sha2** [comment]
hmtl  report is correct, it reports all the parameters correctly as it were applied to the data. We will correct the documentation.

**Comment by smeisler** [comment]
Got it, thanks!
