### ISSUE TITLE
module nifti_smoothing has no output called out_file

### ISSUE THREAD

**Issue by Jinboasltw** [PennLINC/xcp_abcd#65]
Hi experts,
I run an analysis with xcpabcd (version 0.0.1), the log file throw this error to me. Then I change to the latest version on docker hub. Every thing seem ok. So, this may be a bug in the version 0.0.1, right?

Here is my code to run the analysis:
```bash
#!/bin/bash
#User inputs:
bids_root_dir=/media/jinbo/datapool/lab/HBN_Base/ds_01_CUNY/BIDS/rsfMRI
bids_root_dir_output_wd4singularity=/media/jinbo/datapool/lab/HBN_Base/ds_01_CUNY_wd/rsfMRI
subj=$1
nthreads=4

#Run fmriprep
echo ""
echo "Running xcpengine on participant: sub-$subj"
echo ""

#Make xcpabcd directory and participant directory in derivatives folder
if [ ! -d $bids_root_dir/derivatives/xcp_abcd ]; then
    mkdir $bids_root_dir/derivatives/xcp_abcd
fi

if [ ! -d $bids_root_dir/derivatives/xcp_abcd/sub-${subj} ]; then
    mkdir $bids_root_dir/derivatives/xcp_abcd/sub-${subj}
fi
if [ ! -d $bids_root_dir_output_wd4singularity/derivatives/xcp_abcd ]; then
    mkdir $bids_root_dir_output_wd4singularity/derivatives/xcp_abcd
fi

if [ ! -d $bids_root_dir_output_wd4singularity/derivatives/xcp_abcd/sub-${subj} ]; then
    mkdir $bids_root_dir_output_wd4singularity/derivatives/xcp_abcd/sub-${subj}
fi

#Run XCP-ABCD
export SINGULARITYENV_TEMPLATEFLOW_HOME=/home/jinbo/cache_fmriprep/templateflow
unset PYTHONPATH; singularity run --cleanenv --bind $bids_root_dir \
    /media/jinbo/codepool/sigularity_build_wd/xcp_abcd.simg \
    -w $bids_root_dir_output_wd4singularity/derivatives/xcp_abcd/sub-${subj} \
    --resource-monitor \
    --participant_label ${subj} \
    --nthreads $nthreads \
    --omp-nthreads $nthreads \
    --cifti \
    --smoothing 6 \
    -p 36P \
    --despike \
    --lower-bpf 0.01 --upper-bpf 0.08 \
    $bids_root_dir/derivatives/fmriprep $bids_root_dir/derivatives/xcp_abcd/sub-${subj} \
    participant
```

**Comment by a3sha2** [comment]
Hi @Jinboasltw 
pls can you post the error?

**Comment by Jinboasltw** [comment]
Here is the log, you may alread see it in the slack channel.

Running xcpengine on participant: sub-NDARAL897CYV

210514-14:19:20,410 nipype.workflow IMPORTANT:
	 
    Running xcp_abcd version 0.0.1+0.g5dd4acd.dirty:
      * fMRIPrep directory path: /media/jinbo/datapool/lab/HBN_Base/ds_01_CUNY/BIDS/rsfMRI/derivatives/fmriprep.
      * Participant list: ['NDARAL897CYV'].
      * Run identifier: 20210514-141904_cab1be8f-303e-49f6-b793-82e35fa45937.

 Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/xcp_abcd/cli/run.py", line 443, in build_workflow
    name='xcpabcd_wf'
  File "/usr/local/miniconda/lib/python3.7/site-packages/xcp_abcd/workflow/base.py", line 169, in init_xcpabcd_wf
    name="single_bold_" + subject_id + "_wf")
  File "/usr/local/miniconda/lib/python3.7/site-packages/xcp_abcd/workflow/base.py", line 402, in init_single_bold_wf
    name='bold_postprocess_'+ str(ii) + '_wf')
  File "/usr/local/miniconda/lib/python3.7/site-packages/xcp_abcd/workflow/bold.py", line 216, in init_boldpostprocess_wf
    name='clean_data_wf')
  File "/usr/local/miniconda/lib/python3.7/site-packages/xcp_abcd/workflow/postprocessing.py", line 276, in init_post_process_wf
    (smooth_data, outputnode,[('out_file','smoothed_bold')])
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 236, in connect
    raise Exception("\n".join(["Some connections were not found"] + infostr))
Exception: Some connections were not found
Module nifti_smoothing has no output called out_file

**Comment by Jinboasltw** [comment]
Hi, 
I read the git log of the repo, I am curious about why the nifti_smoothing was called.

I am not familar with Python. But, this may be wired, why set a default value to a store_true action? Hope some help to the problem.

I found some manual said:

```python
The following two statements are problematic:

parser.add_argument('--param1', action='store_true', default=True)
parser.add_argument('--param2', action='store_false', default=False)
Wheter you use these paramters on the command line, they will always be True or False, which is not what we want.
```
ref is here: https://jdhao.github.io/2018/10/11/python_argparse_set_boolean_params/

![image](https://user-images.githubusercontent.com/6925515/118483138-42bad180-b748-11eb-8abd-f9571d80b6ca.png)

**Comment by a3sha2** [comment]
thank you @Jinboasltw
